### ISSUE TITLE
feature request: data in min:sec format

### ISSUE THREAD

**Issue by pbienst** [ianxm/emacs-tracker#2]
Apart from data in floating point format, it would be useful to be able to specify data in min:sec format (or hour:min:sec format), e.g. to log the duration of a jogging session.

**Comment by ianxm** [comment]
I'll think about it. 

I had wanted to eventually have a way to combine metrics using formulas (so if you had "running miles" in one metric and "running hours" in another, you could ask for "running miles per hour" by month or other time period. It is more complicated if metrics aren't all just numbers.

one solution is to allow hh:mm:ss but convert them all to decimal hours as I read them in, but then you wouldn't get reporting in hh:mm:ss. better than nothing, but not ideal.

**Comment by ianxm** [comment]
now metrics-tracker will accept hh:mm:ss.ss where hours and fractional seconds are optional. times are converted to decimal hours. let me know if there are issues. closing.
